# Generated by Django 4.2.3 on 2023-10-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_productcategory_productscategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productscategory',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
