# Generated by Django 4.2.5 on 2023-10-16 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_email_is_certificated_emailverification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_is_certificated',
            new_name='is_verified',
        ),
    ]
